version: 2

project_name: git-ssh

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: git-ssh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitHash={{.ShortCommit}}
      - -X main.CompileDate={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: git-ssh
    package_name: git-ssh
    vendor: The git-ssh Authors
    homepage: https://github.com/kuyacarlo/ssh-profile
    maintainer: kuyacarlo
    description: Per-repo SSH identity profiles for GitHub (Orca-safe)
    license: MIT
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/git-ssh/LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
